### ISSUE TITLE
Request for the model

### ISSUE THREAD

**Issue by jimmy-dq** [weihaosky/CycleSiam#1]
Hi Dr. Yuan,
Could you please provide the model trained with the random initialization (Table 3 in your paper). Since this version is fully unsupervised, so I am interested with it. 
Regards

**Comment by weihaosky** [comment]
send me email

**Comment by jimmy-dq** [comment]
Thanks a lot! qiangqwu2-c@my.cityu.edu.hk, for the siamfc evaluation, could you also provide the evaluation code? since thedifferent tracking parameters maybe get various result.
